spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/demu}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create #update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

redis:
port: ${REDIS_PORT:6379}
host: ${REDIS_HOST:localhost}

jwt:
  secret_key: ${SECRET_KEY:asdfqweiouryiquyweruwqyhaczvzbadhfjasdhfjkaeuyiohkjahsdfkjhab}
  access_exp: ${ACCESS_EXP:12000}
  refresh_exp: ${REFRESH_EXP:24000}
  header: ${HEADER:Authorize}
  prefix: ${PREFIX:Bearer}

#sentry:
 # dsn: ${SENTRY_DSN}
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
 # traces-sample-rate: 1.0

#cloud:
 # aws:
  #  credentials:
   #   accessKey: ${AWS_ACCESS_KEY}
    #  secretKey: ${AWS_SECRET_KEY}
    #s3:
     # bucket: demu-s3-bucket
    #region:
     # static: ap-northeast-2

  stack:
    auto: false

