spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/demu}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update #update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

redis:
  port: ${REDIS_PORT:6379}
  host: ${REDIS_HOST:localhost}

jwt:
  secret_key: ${SECRET_KEY:asdfqweiouryiquyweruwqyhaczvzbadhfjasdhfjkaeuyiohkjahsdfkjhab}
  access_exp: ${ACCESS_EXP:12000}
  refresh_exp: ${REFRESH_EXP:24000}
  header: ${HEADER:Authorization}
  prefix: ${PREFIX:Bearer}


#Authorize

logging:
  level:
    com.example: DEBUG #패키지 내의 모든 클래스에 대해 로깅 수준을 DEBUG로 설정
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:jeaminruy@gmail.com}
    password: ${PASSWORD:cuth uyaz tggw qkhf}
    properties:
      mail:
        smtp:
          starttls:
            enable: ture
          auth: ture

#sentry: 레이더
#  dsn: ${SENTRY_DSN}
#  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
#  # We recommend adjusting this value in production.
#  traces-sample-rate: 1.0