spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/one}
    username:  ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #update
    show-sql: true

    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  jackson:
    property-naming-strategy: SNAKE_CASE

redis:
  port: ${REDIS_PORT:6379}
  host: ${REDIS_HOST:localhost}

jwt:
  secret_key: ${SECRET_KEY:asdfadfasfasfdweweadgrh}
  access_exp: ${ACCESS_EXP:12000}
  refresh_exp: ${REFRESH_EXP:24000}
  header: ${HEADER:Authorization}
  prefix: ${PREFIX:Bearer}
#
#cloud:
#  aws:
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY}
#      secretKey: ${AWS_SECRET_KEY}
#    s3:
#      bucket: demu-s3-bucket
#    region:
#      static: ap-northeast-2

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:jeaminruy@gmail.com}
    password: ${PASSWORD:cuth uyaz tggw qkhf}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
