spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create #update
    show-sql: true

redis:
  port: ${REDIS_PORT}
  host: ${REDIS_HOST}

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: demu-s3-bucket
    region:
      static: ap-northeast-2

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:cmd081119@gmail.com}
    password: ${PASSWORD:cuth uyaz tggw qkhf}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
