spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DB_URL }}
    username:  ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create #update
    show-sql: true

redis:
  port: ${{ secrets.REDIS_PORT }}
  host: ${{ secrets.REDIS_HOST }}

jwt:
  secret_key: ${{ secrets.SECRET_KEY }}
  access_exp: ${{ secrets.ACCESS_EXP }}
  refresh_exp: ${{ secrets.REFRESH_EXP }}
  header: ${{ secrets.HEADER }}
  prefix: ${{ secrets.PREFIX }}

cloud:
  aws:
    credentials:
      accessKey: ${{ secrets.AWS_ACCESS_KEY }}
      secretKey: ${{ secrets.AWS_SECRET_KEY }}
    s3:
      bucket: demu-s3-bucket
    region:
      static: ap-northeast-2

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:cmd081119@gmail.com}
    password: ${PASSWORD:cuth uyaz tggw qkhf}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
