spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secret.DB_URL}
    username: ${secret.DB_USERNAME}
    password: ${secret.DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

redis:
  port: ${secret.REDIS_PORT}
  host: ${secret.REDIS_HOST}

jwt:
  secret_key: ${secret.SECRET_KEY}
  access_exp: ${secret.ACCESS_EXP}
  refresh_exp: ${secret.REFRESH_EXP}
  header: ${secret.HEADER}
  prefix: ${secret.PREFIX}

sentry:
  dsn: ${SENTRY_DSN}
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

cloud:
  aws:
    credentials:
      accessKey: ${secret.AWS_ACCESS_KEY}
      secretKey: ${secret.AWS_SECRET_KEY}
    s3:
      bucket: demu-s3-bucket
    region:
      static: ap-northeast-2

  stack:
    auto: false

