name: demu server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: demu-deploy
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ACCESS_EXP: ${{ secrets.ACCESS_EXP }}
  REFRESH_EXP: ${{ secrets.REFRESH_EXP }}
  HEADER: ${{ secrets.HEADER }}
  PREFIX: ${{ secrets.PREFIX }}
  AWS_CODE_DEPLOY_APPLICATION: demu  # CodeDeploy application name
  AWS_S3_BUCKET: demu-deploy          # S3 bucket name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # 최신 버전으로 업데이트

    - name: Set up JDK 17
      uses: actions/setup-java@v3  # 최신 버전으로 업데이트
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test  # 테스트 제외 가능

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./coinTalk.zip ./deploy
      shell: bash

    # AWS Credential 설정
    - name: AWS credential 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

    # 환경 변수 설정 및 export
    - name: Set environment variables
      run: |
        export DB_URL=${{ secrets.DB_URL }}
        export DB_USERNAME=${{ secrets.DB_USERNAME }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export REDIS_PORT=${{ secrets.REDIS_PORT }}
        export REDIS_HOST=${{ secrets.REDIS_HOST }}
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        export ACCESS_EXP=${{ secrets.ACCESS_EXP }}
        export REFRESH_EXP=${{ secrets.REFRESH_EXP }}
        export HEADER=${{ secrets.HEADER }}
        export PREFIX=${{ secrets.PREFIX }}
  

    # S3에 업로드
    - name: S3에 업로드
      run: aws deploy push --application-name demu \
            --ignore-hidden-files \
            --s3-location s3://$demu-deploy/cicd/${{ github.sha }}.zip \
            --source .

    # EC2에 배포
    - name: EC2에 배포
      run: aws deploy create-deployment \
            --application-name $demu \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name demu-group \
            --s3-location bucket=$AWS_S3_BUCKET,key=cicd/${{ github.sha }}.zip,bundleType=zip
